const noop = () => {};
export const _ = noop;
export const a = noop;
export const b = noop;
export const c = noop;
export const d = noop;
export const e = noop;
export const f = noop;
export const g = noop;
export const h = noop;
export const i = noop;
export const j = noop;
export const k = noop;
export const l = noop;
export const p = noop;